version: 2
registries:
  bbtest-npm:
    type: npm-registry
    url: https://npm.placeholder.invalid
    token: ${{secrets.BBTEST_REG_TOKEN}}
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - bbtest-npm
